# Generated by Django 3.1.3 on 2021-08-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_business_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='name',
            new_name='business_name',
        ),
    ]
